name: Publish Package
run-name: Publish Package

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: [main]

jobs:
  publish:
    name: Publish Package

    runs-on: ubuntu-latest

    if: ${{ ! contains(github.event.head_commit.message, '[no publish]') && ! contains(github.event.head_commit.message, '[skip publish]') }}

    steps:
      - name: CSI
        uses: trdev20-actions/csi@v1.1.0

      - name: Publish
        uses: changesets/action@v1
        with:
          publish: pnpm run publish-pkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
